import { Client } from '@notionhq/client';
import { TOKEN, DATABASE_ID } from '../config';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

type ListItem = {
  id: string;
  text: string;
  value: number;
};

const Home: NextPage = (data: any) => {
  // console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const notion = new Client({ auth: TOKEN });

  const getDatabase = () => {
    return notion.databases.query({
      database_id: DATABASE_ID,
    });
  };

  const getPageTitle = (page: any) => {
    return notion.pages.properties.retrieve({
      page_id: page.id,
      property_id: page.properties.name.id,
    });
  };

  const getPageBalance = (page: any) => {
    return notion.pages.properties.retrieve({
      page_id: page.id,
      property_id: page.properties.balance.id,
    });
  };

  const getBankAccounts = async () => {
    const db = await getDatabase();

    return Promise.all(
      db.results.map(async (product) => {
        const title: any = await getPageTitle(product);
        const balance: any = await getPageBalance(product);

        const listItem: ListItem = {
          id: product.id,
          text: title.results[0].title.plain_text,
          value: balance.property_item.rollup.number,
        };

        return listItem;
      }),
    );
  };

  const bankAccounts = await getBankAccounts();

  return {
    props: { bankAccounts },
  };
}
